kind: ConfigMap
apiVersion: v1
metadata:
  name: ssl-proxy-config
  namespace: <%= name %>
data:
  default.conf: |
    server {
      listen       80;
      server_name  {{production_domain}};
      return 301 https://$host$request_uri;
    }
    server {

      proxy_buffers 48 16k;
      proxy_buffer_size 16k;

      listen              443 ssl;
      server_name         {{PRODUCTION_DOMAIN}} meetup.com www.meetup.com *.meetup.com;
      ssl_certificate     /etc/nginx/certs/tls.crt;
      ssl_certificate_key /etc/nginx/certs/tls.key;
      ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
      ssl_ciphers         HIGH:!aNULL:!MD5;
      location /static {
        proxy_pass   http://127.0.0.1:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
      location / {
        proxy_pass   http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
    }
