# # HOW TO USE THIS FILE
#
# This file is a template for creating the 'ssl-proxy' secrets through Kubernetes.
# We use this to volume to storethe SSL certificate and key files for the nginx
# server to use.
#
# Currently there is no way to update/add to an existing secret, so if you want
# to change anything, you'll first have to delete the existing secret:
#
# ```
# > kubectl delete secret ssl-proxy --namespace webplatform
# ```
#
# Then, replace the {{ ____ }} items below with the _base64 encoded_ values
# from the certificate and key files, and create a new secret using `kubectl`.
#
# ```
# TLS_CRT_BASE64=$(cat tls.crt | base64 -b 0 ) \
# TLS_KEY_BASE64=$(cat tls.key | base64 -b 0 ) \
# envtpl < infrastructure/ssl-proxy-secrets.yaml | kubectl apply -f -
# ```
#
# Finally, clean up after yourself - the base64 values should **NOT** be
# committed to version control, and neither should the .crt or .key files.
apiVersion: v1
kind: Secret
metadata:
  name: ssl-proxy-certs
  namespace: <%= name %>
type: Opaque
data:
  tls.crt: {{TLS_CRT_BASE64}}
  tls.key: {{TLS_KEY_BASE64}}