# # HOW TO USE THIS FILE
#
# This file is a template for creating the 'mup-web' secret through Kubernetes.
#
# You will need an up-to-date version of the
# [Google Cloud SDK](https://cloud.google.com/sdk/docs/quickstart-mac-os-x).
# Once installed, set your credentials with Make:
#
# ```
# > make __set-prod __get-credentials
# ```
#
# Currently there is no way to update/add to an existing secret, so if you want
# to change anything, you'll first have to delete the existing secret:
#
# ```
# > kubectl delete secrets/mup-web-secrets --namespace webplatform
# ```
#
# Then, replace the {{ ____ }} items below with the _base64 encoded_ values
# from your environment source, e.g.
#
# ```
# > echo -n $MUPWEB_OAUTH_SECRET | base64
# ```
#
# Save the file with all of the base64-encoded values, then create a new secret
# using the `kubectl` CLI
#
# ```
# > kubectl create -f infrastructure/mup-web-secrets.yaml
# ```
#
# Finally, clean up after yourself - the base64 values should **NOT** be
# committed to version control
apiVersion: v1
kind: Secret
metadata:
  name: webapp-secrets
  namespace: <%= name =>
type: Opaque
data:
  oauth-key: {{ WEBAPP_OAUTH_KEY }}
  oauth-secret: {{ WEBAPP_OAUTH_SECRET }}
  photo-scaler-salt: {{ PHOTO_SCALER_SALT }}
  csrf-secret: {{ CSRF_SECRET }}
  cookie-encrypt-secret: {{ COOKIE_ENCRYPT_SECRET }}  

